name: push

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test
    - name: Publish Nuget Forksen.Qiniu
      run: dotnet nuget push Forksen.Qiniu/bin/Release/Forksen.Qiniu.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.FORKSEN_NUGET_API_KEY}} --skip-duplicate
